version: '3.8'

services:
  app:
    image: beldata/painelbr:latest
    ports:
      - "2800:2800"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

