name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1.12.0 #
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.9.0  
      with:
        context: .
        push: true
        tags: beldata/painelb-api:latest

    - name: Create .env file
      run: |
        cat .env.template | \
        sed "s/your_db_user/${{ secrets.DB_USER }}/g" | \
        sed "s/your_db_password/${{ secrets.DB_PASSWORD }}/g" | \
        sed "s/your_db_name/${{ secrets.DB_NAME }}/g" | \
        sed "s/your_session_secret/${{ secrets.SESSION_SECRET }}/g" > .env

    - name: Setup SSH key
      run: |
        echo "${{ secrets.SSH_KEY_VPS }}" > private_key
        chmod 600 private_key
      env:
        SSH_KEY: ${{ secrets.SSH_KEY_VPS }}

    - name: Verify private key
      run: |
        ssh-keygen -y -e -f private_key

    - name: Copy .env file to VPS
      run: |
        scp -i private_key -o StrictHostKeyChecking=no .env ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/sistran.app/api

    - name: Deploy to VPS
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd /var/www/sistran.app/api && docker-compose pull app && docker-compose up -d"
