name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy api_painelb
        uses: appleboy/ssh-action@v0.1.2
        with: 
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          
          script: |   
            cd /var/www/sistran.app/api
            git pull origin main
            npm install
            npm stop 
            npm start
            echo 'Deployment successful to hetzner'
