name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy api_painelb
        uses: appleboy/ssh-action@v0.1.2
        with: 
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          port: 222
<<<<<<< HEAD
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
=======
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
>>>>>>> c1959a6322be6b65e152ee4e7785755463667ed1
          
          script: |   
            cd api-painelbr
            git pull origin main
            npm install
            npm stop 
            npm start
            echo 'Deployment successful to digital ocean'
